require('config.globals')
require('config.options')
require('config.keymap')
require('config.autocmd')
require('config.lsp')
require('plugins.gruber-darker')
require('plugins.treesitter')
require('plugins.telescope')
require('plugins.dashboard')
-- require('plugins.colorify')  neovim nightly deprecated you my love
require('plugins.lualine')
require('plugins.gitsigns')
require('plugins.indent-blankline')
require('plugins.oil')
